import Head from "next/head";
// import { HomePage } from "../src/components/home/home-page";

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Events app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <HomePage data={data} /> */}

      <main>
        <a href="">
          <img />
          <h2>Events in London</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac
            blandit lorem, eu laoreet quam. Maecenas at auctor lectus, pulvinar
            dapibus ligula
          </p>
        </a>
        <a href="">
          <img />
          <h2>Events in San Francisco</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac
            blandit lorem, eu laoreet quam. Maecenas at auctor lectus, pulvinar
            dapibus ligula
          </p>
        </a>
        <a href="">
          <img />
          <h2>Events in Barcelona</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac
            blandit lorem, eu laoreet quam. Maecenas at auctor lectus, pulvinar
            dapibus ligula
          </p>
        </a>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}
