import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Events app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {data?.map((ev) => (
          <Link key={ev.id} href={`/events/${ev.id}`} passHref>
            <a className="card" href={`/events/${ev.id}`}>
              <div className="image">
                <Image width={600} height={400} alt={ev.title} src={ev.image} />
              </div>
              <div className="content">
                <h2> {ev.title} </h2>
                <p> {ev.description} </p>
              </div>
            </a>
          </Link>
        ))}
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  console.log("events_categories", events_categories);
  return {
    props: {
      data: events_categories,
    },
  };
}
